### ISSUE TITLE
External tool docker Error

### ISSUE THREAD

**Issue by alloka** [kg-construct/KROWN#10]
After adding my tool in KROWN, when I run `./exectool --root=../data-generator/souffle --runs=1 run` I get failed test because of unable to start container despite following the tutorial, the exact error is the following: 127 docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "souffle": executable file not found in $PATH: unknown.
Maybe it's due to my ignorance with docker
[files.zip](https://github.com/user-attachments/files/17000466/files.zip)

thanks in advance!

**Comment by DylanVanAssche** [comment]
I think you have a mistake in your Docker... It complaints about a binary which is not found inside the Docker container.

You try to use some `$PATH` magic to add the binary path to the list of paths for the shell to look for binaries.
You can avoid this by running `cmake install` which properly installs the tool `souffle` inside the Docker. In the Python  class you indeed use `souffle` as binary name, but the Docker container should be able to find it of course in its paths of binaries.

Since you closed this issue, I guess you found the problem and fixed it?
