### ISSUE TITLE
FileNotFoundError when trying to run the execution-framework

### ISSUE THREAD

**Issue by alloka** [kg-construct/KROWN#8]
Hello guys :)

I've been trying to experiment with the tool on windows, I get the following error when I try to run the command  **./exectool --runs=5 --root=my_path run** : 

` File "my_path/KROWN/execution-framework/bench_executor/executor.py", line 66, in __init__
    with open(os.path.join(os.path.dirname(__file__), 'data',
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/aliha/KROWN/execution-framework/bench_executor/data/metadata.schema'`

any help with that?

**Comment by DylanVanAssche** [comment]
Hi!

This file was not committed in git, this has been fixed in the `main` branch, can you please try it?

If there's anything, feel free to let us know!

**Comment by alloka** [comment]
@DylanVanAssche now I get the following error:

`Executing 7 cases:
   1. mappings_10_5                                                                       [  0%     0s]
      ==> Run #1 <==
Case failure due to exception: module 'platform' has no attribute 'freedesktop_os_release'`

**Comment by DylanVanAssche** [comment]
@alloka Which Python version do you use?
A similar problem is reported here: https://github.com/wunderwuzzi23/yolo-ai-cmdbot/issues/7 where it is related to the Python version.

**Comment by DylanVanAssche** [comment]
Can't you use a newer Python version? According to https://github.com/wunderwuzzi23/yolo-ai-cmdbot/issues/7#issuecomment-1459073984 and Python docs (https://docs.python.org/3/library/platform.html#linux-platforms) this was an issue in Python but fixed in Python 3.10 or later.

I added a workaround for these old Python versions on the `main` branch, please try it :)
The platform name and OS is not logged then in the `case-info.txt` file and a warning is logged, but it should continue now.

**Comment by DylanVanAssche** [comment]
Workaround confirmed to be working, closing.
